spring.application.name=demo
spring.docker.compose.enabled=true

# ここを compose.yaml の設定と完全に合わせます
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Flywayを強制的に動かす設定
spring.flyway.enabled=true